# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         tsv
version:      0.3
version_from: tsv
installdirs:  site
requires:
    Getopt::Long:                  0
    List::Util:                    0
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
